"""
CFR TensorBoard Logger for Vesna-Pro (Help Scenario)

Monitors CSV files generated by the Java agent and logs metrics to TensorBoard.

Usage:
    1. Start TensorBoard logging:
       python cfr_tensorboard.py --logdir runs/help_scenario --mode once

    2. View in TensorBoard:
       tensorboard --logdir runs/help_scenario

    3. Monitor in real-time while agent runs:
       python cfr_tensorboard.py --logdir runs/help_scenario --mode monitor
"""

import pandas as pd
import numpy as np
import os
import time
import argparse
from pathlib import Path

try:
    from torch.utils.tensorboard import SummaryWriter
except ImportError:
    try:
        from tensorboardX import SummaryWriter
    except ImportError:
        SummaryWriter = None
        print("WARNING: Neither PyTorch nor tensorboardX found!")
        print("Install with: pip install torch tensorboard")


# OCEAN trait names (must match PolicyLogger.java)
OCEAN_TRAITS = ['openness', 'conscientiousness', 'extraversion', 'agreeableness', 'neuroticism']

# Help scenario actions (must match PolicyLogger.java)
HELP_ACTIONS = [
    'help_bob', 'decline_bob', 'delay_bob',
    'help_carol', 'decline_carol', 'teach_carol',
    'help_dave', 'decline_dave', 'suggest_dave',
]

# Trait descriptions for TensorBoard text
TRAIT_DESCRIPTIONS = {
    'openness': 'Creativity, flexibility, mentoring',
    'conscientiousness': 'Discipline, focus, reliability',
    'extraversion': 'Social engagement, visibility',
    'agreeableness': 'Cooperation, helpfulness',
    'neuroticism': 'Emotional sensitivity, anxiety',
}


class CSVMonitor:
    """Monitor CSV files and log to TensorBoard."""

    def __init__(self, log_dir="runs/help_scenario", csv_dir=None):
        if SummaryWriter is None:
            raise ImportError("TensorBoard writer not available.")

        self.script_dir = Path(__file__).parent
        self.csv_dir = Path(csv_dir) if csv_dir else self.script_dir.parent
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        print(f"[TensorBoard] Log directory: {self.log_dir}")
        print(f"[TensorBoard] View with: tensorboard --logdir {self.log_dir}")

        self.personality_lines = 0
        self.regret_lines = 0

    def get_csv_paths(self):
        personality_csv = self.csv_dir / "personality_evolution.csv"
        regret_csv = self.csv_dir / "cfr_regrets.csv"
        return personality_csv, regret_csv

    def detect_runs(self, df):
        """Detect separate training runs by finding episode resets."""
        runs = []
        run_start = 0
        for i in range(1, len(df)):
            if df.iloc[i]['episode'] == 0 or df.iloc[i]['episode'] < df.iloc[i-1]['episode']:
                runs.append((run_start, i, len(runs) + 1))
                run_start = i
        if run_start < len(df):
            runs.append((run_start, len(df), len(runs) + 1))
        return runs

    def log_single_run(self, df, start_idx, end_idx, run_id, is_regrets=False):
        """Log a single training run to TensorBoard."""
        run_data = df.iloc[start_idx:end_idx].copy()
        run_dir = self.log_dir / f"run_{run_id:03d}"
        run_dir.mkdir(parents=True, exist_ok=True)

        if is_regrets:
            return self._log_regrets_run(run_dir, run_data, run_id)

        # Create separate subdirectory per trait for distinct colors
        for trait in OCEAN_TRAITS:
            if trait not in run_data.columns:
                continue
            trait_dir = run_dir / trait
            writer = SummaryWriter(trait_dir)
            for _, row in run_data.iterrows():
                episode = int(row['episode'])
                writer.add_scalar('personality', row[trait], episode)
            writer.close()

        # Combined view with all traits + reward
        combined_dir = run_dir / "all_traits"
        writer = SummaryWriter(combined_dir)

        for _, row in run_data.iterrows():
            episode = int(row['episode'])
            for trait in OCEAN_TRAITS:
                if trait in row:
                    writer.add_scalar(trait, row[trait], episode)
            if 'total_reward' in row:
                writer.add_scalar('reward', row['total_reward'], episode)

        layout = {
            'OCEAN Personality': {
                'All Traits': ['Multiline', OCEAN_TRAITS],
                'Reward': ['Line', ['reward']],
            }
        }
        writer.add_custom_scalars(layout)

        # Summary text
        if len(run_data) > 1:
            start = run_data.iloc[0]
            final = run_data.iloc[-1]
            arrow = lambda x: '+' if x > 0.01 else '-' if x < -0.01 else '='

            summary_lines = [
                f"Episodes: {len(run_data)}",
                "",
                "STARTING -> FINAL:",
            ]
            for trait in OCEAN_TRAITS:
                s = start.get(trait, 0.5)
                f = final.get(trait, 0.5)
                d = f - s
                summary_lines.append(
                    f"  {trait:20s}: {s:.3f} -> {f:.3f}  ({arrow(d)}{abs(d):.3f})"
                )
            summary_lines.append(f"\nTotal Reward: {run_data['total_reward'].sum():.1f}")
            writer.add_text('summary/training', '\n'.join(summary_lines))

        writer.close()
        return len(run_data)

    def _log_regrets_run(self, run_dir, run_data, run_id):
        """Log regret data for a single run."""
        writer = SummaryWriter(run_dir / "regrets")

        # Group actions by person
        persons = {
            'Bob': ['help_bob', 'decline_bob', 'delay_bob'],
            'Carol': ['help_carol', 'decline_carol', 'teach_carol'],
            'Dave': ['help_dave', 'decline_dave', 'suggest_dave'],
        }

        for _, row in run_data.iterrows():
            episode = int(row['episode'])

            for person, actions in persons.items():
                for action in actions:
                    if action in row:
                        writer.add_scalar(f'regrets/{person}/{action}', row[action], episode)

                # Implied strategy (regret matching)
                regrets = [max(0, row.get(a, 0)) for a in actions]
                total = sum(regrets)
                if total > 0.001:
                    for i, a in enumerate(actions):
                        prob = regrets[i] / total
                        writer.add_scalar(f'strategy/{person}/{a}', prob, episode)

        writer.close()
        return len(run_data)

    def log_personality_data(self, df):
        if df.empty:
            return
        runs = self.detect_runs(df)
        print(f"[TensorBoard] Detected {len(runs)} training runs")
        total = 0
        for start, end, rid in runs:
            count = self.log_single_run(df, start, end, rid)
            total += count
            print(f"  Run {rid}: {count} episodes")
        print(f"[TensorBoard] Logged {total} personality entries")

    def log_regret_data(self, df):
        if df.empty:
            return
        runs = self.detect_runs(df)
        total = 0
        for start, end, rid in runs:
            run_data = df.iloc[start:end].copy()
            run_dir = self.log_dir / f"run_{rid:03d}"
            count = self._log_regrets_run(run_dir, run_data, rid)
            total += count
        print(f"[TensorBoard] Logged {total} regret entries")

    def process_existing_data(self):
        personality_path, regret_path = self.get_csv_paths()
        print("\n=== Processing Existing Data ===")

        if personality_path.exists():
            df = pd.read_csv(personality_path)
            print(f"Found {len(df)} episodes in {personality_path.name}")
            self.log_personality_data(df)
        else:
            print(f"No personality data at {personality_path}")

        if regret_path.exists():
            df = pd.read_csv(regret_path)
            print(f"Found {len(df)} regret entries in {regret_path.name}")
            self.log_regret_data(df)
        else:
            print(f"No regret data at {regret_path}")

        print("=== Processing Complete ===\n")

    def monitor(self, interval=5):
        print(f"\n=== Monitoring CSV files (interval: {interval}s) ===")
        print("Press Ctrl+C to stop...\n")

        personality_path, regret_path = self.get_csv_paths()
        if personality_path.exists():
            self.personality_lines = len(pd.read_csv(personality_path))
        if regret_path.exists():
            self.regret_lines = len(pd.read_csv(regret_path))

        try:
            while True:
                if personality_path.exists():
                    df = pd.read_csv(personality_path)
                    if len(df) > self.personality_lines:
                        self.log_personality_data(df.iloc[self.personality_lines:])
                        self.personality_lines = len(df)

                if regret_path.exists():
                    df = pd.read_csv(regret_path)
                    if len(df) > self.regret_lines:
                        self.log_regret_data(df.iloc[self.regret_lines:])
                        self.regret_lines = len(df)

                time.sleep(interval)
        except KeyboardInterrupt:
            print(f"\n=== Stopped. Logs at: {self.log_dir} ===")


def main():
    parser = argparse.ArgumentParser(description='CFR TensorBoard Logger')
    parser.add_argument('--logdir', default='runs/help_scenario')
    parser.add_argument('--csv-dir', default=None)
    parser.add_argument('--mode', choices=['once', 'monitor'], default='once')
    parser.add_argument('--interval', type=int, default=5)
    args = parser.parse_args()

    monitor = CSVMonitor(log_dir=args.logdir, csv_dir=args.csv_dir)
    if args.mode == 'once':
        monitor.process_existing_data()
    else:
        monitor.process_existing_data()
        monitor.monitor(interval=args.interval)


if __name__ == '__main__':
    main()
